apiVersion: v1
kind: Service
metadata:
  name: aws-eks-pipeline-service
spec:
  selector:
    app: aws-eks-pipeline
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080